---
Name: innoweb-enhancedrss
---
SilverStripe\Control\RSS\RSSFeed_Entry:
  extensions:
    - Innoweb\EnhancedRSS\Extensions\RSSFeedEntryExtension

SilverStripe\CMS\Controller\ContentController:
  extensions:
    - Innoweb\EnhancedRSS\Extensions\ControllerExtension
